version: 0.1

environment_variables:
  plaintext:
    NEXUS_USERNAME: "your-Nexus-user-name"
    NEXUS_PASSWORD: "your-Nexus-password"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean buildnumber:create buildnumber:create-metadata install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn install -s s3://aws-build-secrets/maven/settings.xml
artifacts:
  files:
    - target/test-app-1.0-SNAPSHOT-r*.jar
