version: 0.1

environment_variables:
  plaintext:
    NEXUS_USERNAME: "your-Nexus-user-name"
    NEXUS_PASSWORD: "your-Nexus-password"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase ...
  pre_build:
    commands:
      - aws s3 cp s3://aws-build-secrets/settings.xml ~/.m2/settings.xml
      - ls -lhr ~/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn clean buildnumber:create buildnumber:create-metadata
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s ~/.m2/settings.xml package
artifacts:
  files:
    - target/test-app-1.0.*.jar
